POST http://localhost:3000/api/v1/dropbox/filesGet HTTP/1.1

###
POST http://localhost:3000/api/v1/dropbox/fileGet HTTP/1.1


###
POST https://content.dropboxapi.com/2/files/get_preview HTTP/1.1
#Content-Type: application/json
Dropbox-API-Arg: {"path": "/sf - chej consultor, c.a. - oficina/chej consultor, c.a/ord. de servicio (digitalizadas)/etiquetas yecary, c.a/ser-yec651.pdf"}

##{"path": "/sf - chej consultor, c.a. - oficina/chej consultor, c.a/ord. de servicio (digitalizadas)/etiquetas yecary, c.a/ser-yec651.pdf"}
